services:
  # Base de Datos
  db_monitor:
    image: postgres:15
    container_name: monitor_db
    restart: always
    environment:
      POSTGRES_USER: admin_tennis
      POSTGRES_PASSWORD: mi_clave_secreta_123
      POSTGRES_DB: monitor_precios_db
    ports:
      - "5433:5432"
    volumes:
      - monitor_postgres_data:/var/lib/postgresql/data

  # El Bot Rastreador
  tennis_bot:
    build: ./bot
    container_name: tennis_bot
    restart: always
    depends_on:
      - db_monitor
    env_file:
      - .env
    environment:
      - DB_HOST=db_monitor  # Muy importante: dentro de Docker la DB se llama 'db_monitor'
      - DB_PORT=5432        # Internamente Postgres siempre usa el 5432

volumes:
  monitor_postgres_data: